#docker-compose -f docker/dev/docker-compose.yml up --build
version: '2.0'

services:
  front_end_moniciones_liturgicas:
    build: 
      context: ../../
      dockerfile: docker/dev/Dockerfile
    ports:
      - 3003:3003
    expose:
      - 3003  
